### ISSUE TITLE
v6.0.0版本以后打开闪退

### ISSUE THREAD

**Issue by Umtherman** [ichenhe/wear-gallery#17]
- [√] 我已确认手机与手表应用版本相同。
- [√] 我已经给予了需要的权限（存储）

**错误描述**
6.0版本以上，应用打开闪退。（刚开始的时候能够正常使用，某一天表盘突然卡住，图库也无法加载）清除数据后重新打开，“显示数据升级中”之后就无法打开了
但是6.0版本以下可使用。

**期望的行为**
希望能够解决问题，6.0版真的很棒
自定义表盘的功能很喜欢

**手表（务必填写下列信息）：**
 - 设备：[TicWatch E]
 - 系统：[Wear OS 2.23]
- 应用版本：[v6.0.0及其以上]

**Comment by liangchenhe55** [comment]
非常感谢您的喜爱。我也是刚刚考完试，这边工作方面还有一些业务急需处理。
我尽力在春节假期期间让 v6 版本达到能够正式使用的状态。

**Comment by ichenhe** [comment]
目前更新到了 v6.1.6
 
这个问题应该不存在了
