### ISSUE TITLE
6.01-preview手表端读取图片失败

### ISSUE THREAD

**Issue by wanglanhua1** [ichenhe/wear-gallery#18]
- [y] 我已确认手机与手表应用版本相同。
- [y] 我已经给予了需要的权限，例如：自启/后台运行/关联唤醒。

**错误描述**
手机与手表连接后手表端只能读取到少部分相册，其余的相册在手表上转一会圈之后就显示点击重试

**复现**
如何出现错误：
1. 连接手机和手表
2. 点击相册（例如Sharemedia，twitter）
3. 读取失败

**期望的行为**
手表成功读取相册并显示

**屏幕截图**
如果有可能请提供图片。

**手机（务必填写下列信息）：**
 - 设备：小米9
 - 系统：miui12.5 21.2.3（安卓R）

**手表（务必填写下列信息）：**
 - 设备：小米手表
 - 系统：wear os（小米第五到第七次ota都有问题）
- 应用版本：6.01-preview

**其他内容**
手表读取相册的时候手机弹出了正在读取的toast

**Comment by MichaelVector** [comment]
我也遇到了同样的问题
手机：红米K30Pro
手表：Ticwatch Pro3
应用版本：6.01-preview

**Comment by ichenhe** [comment]
不少人反馈这个问题了，但是我一直没能复现。
下一版本会改掉读取手机图片的策略再试试吧，正在做。抱歉～

**Comment by ichenhe** [comment]
v6.1.2 版本起修复了这个问题。请使用新版本测试～
