### ISSUE TITLE
Not working on Huawei phone 

### ISSUE THREAD

**Issue by Painko** [ichenhe/wear-gallery#28]
- [ ] I have confirmed that the phone is the same as the watch app version.
- [ ] I have confirmed that I have given the required permissions.

**Describe the bug**
Not working on Huawei phone  after I clicked learn 404 website showed up 

**Phone (please complete the following information):**
 - Device: [Huawei P30 Lite]
 - OS: [Andoid 10]

**Watch(please complete the following information):**
 - Device: [Fossil gen 6]
 - OS: [Wear OS 2]
- App Version: [6.2.0]

**Comment by ichenhe** [comment]
This is a intent behavior. For details please visit [here](https://wg.chenhe.me/zh/announcement/huawei/) (zh only).

You can still use the watch client with LAN transfer.
