### ISSUE TITLE
Synchronization doesn't work on new version 

### ISSUE THREAD

**Issue by MrNyawka** [ichenhe/wear-gallery#31]
I updated the mobile app to 6.3.0 and synchronization between phone and watch stopped working (pictures from phone not updating and not showing)
Then I downloaded previous version (6.2.0) and there it works properly even when app version on watch is 6.3.0
Phone: Redmi Note 8 Pro (all permissions are granted)
Watch: Ticwatch Pro 3 GPS

**Comment by Dark1638** [comment]
I also cant syncronise on latest version
Poco x3pro and huawei watch w2

**Comment by ichenhe** [comment]
I have noted this issue. It may be necessary to release a new version with a log export feature to help investigate.
I will deal with this issue as soon as possible.

Sorry for that

**Comment by LK024** [comment]
> I have noted this issue. It may be necessary to release a new version with a log export feature to help investigate.
> I will deal with this issue as soon as possible.
> 
> Sorry for that

I investigated a bit and from the settings not only does the app no ​​longer have permissions, but they can't even be granted, as if the app doesn't require them
