### ISSUE TITLE
建议添加对腕上哔哩图片存储位置的识别

### ISSUE THREAD

**Issue by DoyoDia** [ichenhe/wear-gallery#36]
自动识别图片库文件夹既然都支持qq了，可以也支持一下腕上bili嘛

**Comment by ichenhe** [comment]
你好，感谢反馈。

需要澄清的是腕间图库不会主动适配任何 App，也不会扫描存储目录。图片是从系统媒体库读取的。Android 系统会自动扫描标准目录中符合规则的媒体文件并建立索引，这样性能更好，也是标准做法。

能显示 QQ 图片大概率因为 QQ 把图片保存到了符合规则的目录下。故腕间图库不会主动适配腕上哔哩。

如有疑问请联系腕上哔哩开发者。谢谢。
