### ISSUE TITLE
始终提示手表响应超时

### ISSUE THREAD

**Issue by Chris-Bill** [ichenhe/wear-gallery#6]
- [x] 我已确认手机与手表应用版本相同。
- [x] 我已经给予了需要的权限，例如：自启/后台运行/关联唤醒。

**错误描述**
始终提示手表响应超时

**复现**
在手机端选择要传输的图片，点击发送，手表端出现接收提示，但不久之后手机端提示“ **发送出错** 手表响应超时”，此时手表端依旧在接收提示状态

**手机（务必填写下列信息）：**
 - 设备：Samsung Galaxy S III (SCH-R530U)
 - 系统：CyanogenMod 12.1-Android 5.1.1 

**手表（务必填写下列信息）：**
 - 设备：Moto 360 1st Gen
 - 系统：Android Wear 1.4.0.2580363
- 应用版本：v5.1.1210

**Comment by liangchenhe55** [comment]
现在传输这块确实不够稳定。建议使用内网传输看看。
近期比较忙没抽出时间处理这事。

**Comment by ichenhe** [comment]
v6.1.2 版本起重写批量发送的逻辑，之前的问题应该都已经不再有意义。
烦请使用最新版测试。

如果依然有错误欢迎开新的 issue，谢谢～
